#应用port以及访问上下文配置
server: 
  port: 8080
  context-path: /ifun

#注入数据源配置
spring: 
  datasource:
    name: test
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
 
#指定当前激活的环境配置文件
  profiles: 
    active: dev
 
#mybatis配置
mybatis:
  mapperLocations: classpath*:mybatis/*.xml
  typeAliasesPackage: com.ifunyoung
  
#获取系统自定义参数
SYSTEM.APPLICATION.URL: www.baidu.com
